### ISSUE TITLE
Tweaks to level boss system

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/SuggestionBox#2]
The bosses in Randamu are a welcome change of pace every four levels, but fairly buggy in practice. It's all too common to have one of the following happen: 

- Accidentally triggering the boss fight outside of the boss arena and being softlocked
- The boss escaping through the holes you made in order to get inside the arena
- The player trapping the boss in blocks before initiating the fight, making the encounter trivial

These issues I feel warrant a small change to the way bosses are handled in Randamu, so here's my idea:

When the boss is spawned, the game would set a "boss range" inside the arena where the boss is. If the game detects that the player's position is inside this boss range, the boss's hideout is regenerated, replacing any tiles destroyed in order to get inside. Maybe this would also cut out the music, or start playing an ominous pre-boss song?

Once this happens, the game would then prevent the player from placing or destroying blocks, and also make the boss vulnerable to attacks, allowing for the fight to be initiated whenever the player is ready.

**Comment by TrashboxBobylev** [comment]
The fixes to all three points have been implemented in 1.42.3 (not in a way described in this suggestion tho).
