### ISSUE TITLE
Make the sheep and the flying Gaudi's laser immune to the Little Man

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/SuggestionBox#3]
In the case of the sheep, the Little Man tends to trigger the sheep no matter how careful you're trying to be, and in the case of the Gaudi laser he causes the segments to spread out in random directions against the player's will, possibly hitting the player in the process.

**Comment by TrashboxBobylev** [comment]
Implemented in 1.42.3.
