### ISSUE TITLE
Special keys for polar star and nemesis

### ISSUE THREAD

**Issue by Descharges** [DoukutsuRandamu/SuggestionBox#6]
When playing with a controller, changing to these frequent use weapons can be bothersome. Why not have special keys to use thoses two weapong ? So we could have a mapping like LT to place block, RT to destroy them, and one of the face button to shoot the regular weapon.

**Comment by TrashboxBobylev** [comment]
Well, the problem with that is that I don't have controller so I can't really test how well new buttons would work.
